trigger:
- main

pool:
  vmImage: ubuntu-latest
  
stages:
- stage: Build
  jobs:
  - job: build
    displayName: Build app
    
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: Install Node
      
    - task: Npm@1
      inputs:
        command: 'install'
      displayName: Run npm install
      
      
- stage: deploy_staging
  displayName: Deploy to staging
  jobs:
  - job: deploy
    displayName: Deploy and test
    steps:
    - checkout: none
    - download: none
    
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: drop
      displayName: Download Artifacts
      
      
    - task: AzureStaticWebApp@0
      inputs:
        app_location: frontend
        skip_app_build: true
        azure_static_web_apps_api_token: $(token-variable)
        deployment_environment: staging
        workingDirectory: $(Pipeline.Workspace)
 
 variables:
  swa_url: $[ stageDependencies.deploy_staigng.deploy.outputs['AzureStaticWebApp.static_web_app_url']]
  deploymentToken: $[ stageDependencies.Build.IaC.outputs['deploy.deploymentToken'] ]
        
 - stage: review_by_user
   displayName: Review stage
   jobs: 
   - job: waitForValidation
     displayName: Wait for external validation
     pool: server
     timeoutInMinutes: 1440 # job times out in a day
     inputs:
       notifyUsers: |
         $(Build.RequestedForEmail)
       instructions: |
         Please validate the recent changes to your static web app and click resume. 
         
         $(swa_url)
        onTimeout: 'reject'
        
- stage: deploy_production
  displayName: Deploy to production
  jobs:
  - job: deploy
    displayName: Deploy
    steps:
    - checkout: none
    - download: none
    
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: drop
      displayName: Download Artifacts
      
      
    - task: AzureStaticWebApp@0
      inputs:
        app_location: frontend
        skip_app_build: true
        azure_static_web_apps_api_token: $(token-variable)
        workingDirectory: $(Pipeline.Workspace)
 
      