name: Azure Static Web Apps CI/CD

trigger: 
 - None

pr:
  branches:
    include:
      - web-app-setup


stages:
- stage: deploy_staging
  displayName: Deploy to staging
  jobs:
  - job: build_and_deploy_job
    condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))
    displayName: Build and Deploy Job
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Azure-Static-Web-Apps-orange-bush-00cad8003-variable-group
    steps:
    - checkout: self
      submodules: true
    - task: AzureStaticWebApp@0
      inputs:
        deployment_environment: staging
        skip_app_build: true
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_BUSH_00CAD8003)
        app_location: "/Static-Web-App/src" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "/Static-Web-App/build" # Built app content directory - optional

- stage: review_by_user
  displayName: Review stage
  jobs: 
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 1440 # job times out in a day
    steps:   
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
          notifyUsers: |
              marhta.lasia@prorail.nl
          instructions: 'Please validate the build configuration and resume'
          onTimeout: 'reject'

- stage: deploy_production
  displayName: Deploy to production
  jobs:
  - job: build_and_deploy_job
    condition: or(eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))
    displayName: Build and Deploy Job
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Azure-Static-Web-Apps-orange-bush-00cad8003-variable-group
    steps:
    - checkout: self
      submodules: true
    - task: AzureStaticWebApp@0
      inputs:
        skip_app_build: true
        azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_BUSH_00CAD8003)
        app_location: "/Static-Web-App/src" # App source code path
        api_location: "" # Api source code path - optional
        output_location: "/Static-Web-App/build" # Built app content directory - optional
